import test from 'node:test';import assert from 'node:assert/strict';
// @ts-ignore Pure JS migration module tested using synthetic accounts only.
import {reconcileClerkImports} from '../../../scripts/migration/clerk-reconcile.mjs';
// @ts-ignore Pure JS import-policy checks.
import {verifyImportedUser} from '../../../scripts/migration/auth-import-policy.mjs';
const ref='mnotoltpythkayguhnrk',app='app_3J2K0Pon22KSbO5Lt72HQbAI8e8',instance='ins_3J2MGZqJla2mM66OUuT7rYwK4O0';
function fixture(){const body={external_id:ref+':old-uuid',email_address:['synthetic@example.invalid'],email_address_identification_status:['verified'],password_digest:'$2b$10$'+'A'.repeat(53),password_hasher:'bcrypt',banned:false};return {plan:{format:'seekoffer.clerk.production-import-plan.v2',applicationId:app,productionInstanceId:instance,users:[{sourceRef:ref,legacyUserId:'old-uuid',body}]},target:{id:'user_synthetic',external_id:body.external_id,password_enabled:true,banned:false,email_addresses:[{email_address:body.email_address[0],verification:{status:'verified'}}]},checkpoint:{applicationId:app,productionInstanceId:instance,sourceRef:ref,legacyUserId:'old-uuid',clerkUserId:'user_synthetic'}};}
test('existing imported users never receive old snapshot password hashes on replay',()=>{const {plan,target,checkpoint}=fixture();const action=reconcileClerkImports(plan,[target],[checkpoint])[0];assert.equal(action.action,'preserve');assert.equal(action.passwordUpdateForbidden,true);assert.equal('body'in action,false);assert.equal(JSON.stringify(action).includes('password_digest'),false);});
test('fresh accounts preserve source UUID and email state; collisions never merge pools',()=>{const {plan,target,checkpoint}=fixture();const action=reconcileClerkImports(plan,[],[])[0];assert.equal(action.action,'create');assert.equal(action.body.external_id,plan.users[0].body.external_id);assert.throws(()=>reconcileClerkImports(plan,[{...target,external_id:'other-project:same-id'}],[]));assert.throws(()=>reconcileClerkImports(plan,[target],[]));assert.throws(()=>reconcileClerkImports(plan,[],[checkpoint]));});
test('source bans and verified email cannot silently weaken during reconciliation',()=>{const {plan,target,checkpoint}=fixture();plan.users[0].body.banned=true;assert.throws(()=>reconcileClerkImports(plan,[target],[checkpoint]));target.banned=true;target.email_addresses[0].verification.status='unverified';assert.throws(()=>reconcileClerkImports(plan,[target],[checkpoint]));});
test('new reserved users cannot be silently verified; resumed users may retain their own later verification',()=>{const {plan,target}=fixture();const source=plan.users[0];source.body.email_address_identification_status=['reserved'];assert.throws(()=>verifyImportedUser(source,target));assert.equal(verifyImportedUser(source,target,{allowTargetUpgrade:true}).passwordUpdateForbidden,true);target.email_addresses[0].verification.status='unverified';assert.equal(verifyImportedUser(source,target).clerkUserId,target.id);assert.throws(()=>verifyImportedUser(source,{...target,password_enabled:false}));});
