import {describe,it,expect,vi,afterEach} from 'vitest';
import {createClerkSessionBridge,clerkPortalUrl,D1SessionChangedError,createPinnedD1Client,type ClerkBrowser} from '../lib/clerk-d1-session';
import {backendKind} from '../lib/backend-mode';
const id='00000000-0000-4000-8000-000000000001';
const profile=()=>({id,nickname:'合成账号',age:'',undergraduate_school:'',major:'',grade:'大四',target_major:'',target_region:'',sync_revision:1});
function sdk():ClerkBrowser{return {load:async()=>{},session:{id:'sess_synthetic',getToken:async()=>'synthetic-token'},user:{id:'user_clerk_synthetic',primaryEmailAddress:{emailAddress:'synthetic@example.invalid'}},addListener:()=>()=>{},signOut:async()=>{}};}
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();vi.resetModules();});
describe('Clerk to original D1 identity bridge',()=>{
 it('uses the backend original UUID and never caches Clerk tokens as application identity',async()=>{const c=sdk(),bridge=createClerkSessionBridge(async()=>c,async token=>{expect(token).toBe('synthetic-token');return profile();});const session=await bridge.hydrate();expect(session?.userId).toBe(id);expect(JSON.stringify(session)).not.toContain('synthetic-token');expect(JSON.stringify(session)).not.toContain('user_clerk_synthetic');});
 it('coalesces concurrent hydration and rejects missing profile or failed reads',async()=>{const c=sdk(),fetch=vi.fn(async()=>profile());const bridge=createClerkSessionBridge(async()=>c,fetch);await Promise.all([bridge.hydrate(),bridge.hydrate(),bridge.hydrate()]);expect(fetch).toHaveBeenCalledTimes(1);await expect(createClerkSessionBridge(async()=>c,async()=>null).hydrate()).rejects.toThrow('关联');await expect(createClerkSessionBridge(async()=>c,async()=>{throw Error('offline');}).hydrate()).rejects.toThrow('offline');});
 it('rejects a response from an account switched or signed out while the request was pending',async()=>{const c=sdk();let release!:(v:unknown)=>void;const bridge=createClerkSessionBridge(async()=>c,()=>new Promise(resolve=>{release=resolve;}));const pending=bridge.hydrate();await vi.waitFor(()=>expect(release).toBeTypeOf('function'));c.session=null;c.user=null;release(profile());await expect(pending).rejects.toBeInstanceOf(D1SessionChangedError);});
 it('an absent authenticated session never reads the profile API',async()=>{const c=sdk();c.session=null;const fetch=vi.fn();expect(await createClerkSessionBridge(async()=>c,fetch).hydrate()).toBeNull();expect(fetch).not.toHaveBeenCalled();});
 it('portal redirects stay on the product domain without forwarding query tokens',()=>{const url=new URL(clerkPortalUrl('https://migration.seekoffer.com.cn/account?token=synthetic#access_token=private'));expect(url.origin).toBe('https://accounts.seekoffer.com.cn');expect(url.searchParams.get('redirect_url')).toBe('https://migration.seekoffer.com.cn/account');expect(()=>clerkPortalUrl('https://seekoffer.com.cn.evil.invalid/')).toThrow();expect(()=>clerkPortalUrl('http://localhost/')).toThrow();});
 it('pins mutations to the verified original user and rejects cross-account dispatch',async()=>{const c=sdk(),fetcher=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>Response.json({sync_revision:2}));const factory=createPinnedD1Client(async()=>c,()=>id,'https://migration.seekoffer.com.cn',fetcher);await expect(factory('00000000-0000-4000-8000-000000000002')).rejects.toBeInstanceOf(D1SessionChangedError);const client=await factory(id);await client.updateProfile(1,{nickname:'update A'});expect(new Headers(fetcher.mock.calls[0][1]?.headers).get('authorization')).toBe('Bearer synthetic-token');c.session={id:'other-session',getToken:async()=>'other-token'};await expect(client.updateProfile(2,{nickname:'stale A'})).rejects.toBeInstanceOf(D1SessionChangedError);expect(fetcher).toHaveBeenCalledTimes(1);});
 it('D1 mode cannot instantiate the legacy Supabase client',async()=>{vi.stubEnv('NEXT_PUBLIC_BACKEND_PROVIDER','d1');const {getSupabaseBrowserClient}=await import('../lib/supabase-browser');expect(()=>getSupabaseBrowserClient()).toThrow('阻止连接旧服务');expect(()=>backendKind('typo')).toThrow();});
});
