import {it,expect,vi} from 'vitest';
import {createClerkAuthFlow,clerkFlowError,type AuthClerk} from '../lib/clerk-auth-flow';
import type {UserSession} from '../lib/user-session';
const email='synthetic@example.invalid',sid='sess_synthetic';
const userSession:UserSession={loggedIn:true,authProvider:'password',userId:'00000000-0000-4000-8000-000000000001',email,phone:'',profile:{nickname:'Test',age:'',undergraduateSchool:'',major:'',grade:'大四',targetMajor:'',targetRegion:''}};
function setup(){
 const signIn={create:vi.fn().mockResolvedValue({status:'complete',createdSessionId:sid}),prepareFirstFactor:vi.fn().mockResolvedValue({}),attemptFirstFactor:vi.fn().mockResolvedValue({status:'complete',createdSessionId:sid}),prepareSecondFactor:vi.fn().mockResolvedValue({}),attemptSecondFactor:vi.fn().mockResolvedValue({status:'complete',createdSessionId:sid})};
 const signUp={create:vi.fn().mockResolvedValue({status:'missing_requirements'}),prepareEmailAddressVerification:vi.fn().mockResolvedValue({}),attemptEmailAddressVerification:vi.fn().mockResolvedValue({status:'complete',createdSessionId:sid})};
 const sdk={load:async()=>{},session:null,client:{signIn,signUp},setActive:vi.fn(async({session}:{session:string})=>{sdk.session={id:session,getToken:async()=>'synthetic-token'};sdk.user={id:'user_synthetic',primaryEmailAddress:{emailAddress:email}};}),addListener:()=>()=>{},signOut:vi.fn(async()=>{sdk.session=null;sdk.user=null;})} as AuthClerk;
 const confirm=vi.fn(async()=>{expect(sdk.session?.id).toBe(sid);return userSession;});
 return{sdk,signIn,signUp,confirm,flow:createClerkAuthFlow(async()=>sdk,confirm)};
}
it('password login activates a session then confirms the business profile before success',async()=>{const s=setup();expect(await s.flow.password(email,'original-password')).toEqual({status:'signed_in',session:userSession});expect(s.sdk.setActive).toHaveBeenCalledExactlyOnceWith({session:sid});expect(s.confirm).toHaveBeenCalledTimes(1);});
it('a valid auth session with a failed D1 profile cannot report login success, and can resume sync',async()=>{const s=setup();s.confirm.mockRejectedValueOnce(Error('D1 unavailable'));await expect(s.flow.password(email,'password')).rejects.toThrow('D1 unavailable');expect(s.sdk.session?.id).toBe(sid);expect((await s.flow.resume()).status).toBe('signed_in');expect(s.signIn.create).toHaveBeenCalledTimes(1);});
it.each(['needs_client_trust','needs_second_factor'])('%s remains incomplete until the email verification succeeds',async status=>{const s=setup();s.signIn.create.mockResolvedValue({status,supportedSecondFactors:[{strategy:'email_code',emailAddressId:'email_synthetic'}]});expect(await s.flow.password(email,'password')).toEqual({status:'challenge',challenge:{kind:'device',email}});expect(s.sdk.setActive).not.toHaveBeenCalled();expect(s.confirm).not.toHaveBeenCalled();expect(s.signIn.prepareSecondFactor).toHaveBeenCalledExactlyOnceWith({strategy:'email_code',emailAddressId:'email_synthetic'});s.signIn.attemptSecondFactor.mockRejectedValueOnce({errors:[{code:'form_code_incorrect'}]});await expect(s.flow.verify(email,'000000')).rejects.toMatchObject({errors:[{code:'form_code_incorrect'}]});expect(s.confirm).not.toHaveBeenCalled();expect(s.sdk.setActive).not.toHaveBeenCalled();expect((await s.flow.verify(email,'123456')).status).toBe('signed_in');expect(s.signIn.attemptSecondFactor).toHaveBeenLastCalledWith({strategy:'email_code',code:'123456'});});
it('device trust resend reuses the same second factor without restarting password authentication',async()=>{const s=setup();s.signIn.create.mockResolvedValue({status:'needs_client_trust',supportedSecondFactors:[{strategy:'email_code',emailAddressId:'email_synthetic'}]});await s.flow.password(email,'synthetic-password');await expect(s.flow.resend('other@example.invalid')).rejects.toThrow('验证步骤');await s.flow.resend(email);expect(s.signIn.create).toHaveBeenCalledTimes(1);expect(s.signIn.prepareSecondFactor).toHaveBeenCalledTimes(2);expect(s.signIn.prepareFirstFactor).not.toHaveBeenCalled();expect(s.confirm).not.toHaveBeenCalled();});
it.each([undefined,null,[],[{strategy:'phone_code'}],[{strategy:'email_code'}]])('device trust with unusable factors fails closed: %j',async factors=>{const s=setup();s.signIn.create.mockResolvedValue({status:'needs_client_trust',supportedSecondFactors:factors});await expect(s.flow.password(email,'synthetic-password')).rejects.toThrow('安全验证');expect(s.sdk.setActive).not.toHaveBeenCalled();expect(s.confirm).not.toHaveBeenCalled();expect(s.signIn.prepareSecondFactor).not.toHaveBeenCalled();});
it('a device email delivery failure cannot authenticate or accept an unprepared code',async()=>{const s=setup();s.signIn.create.mockResolvedValue({status:'needs_client_trust',supportedSecondFactors:[{strategy:'email_code',emailAddressId:'email_synthetic'}]});s.signIn.prepareSecondFactor.mockRejectedValueOnce(Error('mail unavailable'));await expect(s.flow.password(email,'synthetic-password')).rejects.toThrow('mail unavailable');await expect(s.flow.verify(email,'123456')).rejects.toThrow('验证步骤');expect(s.signIn.attemptSecondFactor).not.toHaveBeenCalled();expect(s.confirm).not.toHaveBeenCalled();});
it('wrong passwords, unsupported second factors and incomplete statuses cannot produce a local session',async()=>{for(const attempt of [{status:'needs_second_factor',supportedSecondFactors:[{strategy:'unsupported'}]},{status:'needs_identifier'}]){const s=setup();s.signIn.create.mockResolvedValue(attempt);await expect(s.flow.password(email,'password')).rejects.toThrow();expect(s.confirm).not.toHaveBeenCalled();}const s=setup();s.signIn.create.mockRejectedValue(Error('wrong password'));await expect(s.flow.password(email,'wrong')).rejects.toThrow();expect(s.signIn.prepareSecondFactor).not.toHaveBeenCalled();});
it('email-code login binds verification to the requested address',async()=>{const s=setup();s.signIn.create.mockResolvedValue({status:'needs_first_factor',supportedFirstFactors:[{strategy:'email_code',emailAddressId:'email_synthetic'}]});expect((await s.flow.emailCode(email)).status).toBe('challenge');await expect(s.flow.verify('another@example.invalid','123456')).rejects.toThrow('验证步骤');expect(s.confirm).not.toHaveBeenCalled();expect((await s.flow.verify(email,'123456')).status).toBe('signed_in');});
it('signup requires email verification and keeps the current new-password length rule',async()=>{const s=setup();await expect(s.flow.signUp(email,'short')).rejects.toThrow('15');expect(s.signUp.create).not.toHaveBeenCalled();expect((await s.flow.signUp(email,'long-synthetic-password')).status).toBe('challenge');expect(s.signUp.prepareEmailAddressVerification).toHaveBeenCalledExactlyOnceWith({strategy:'email_code'});expect(s.confirm).not.toHaveBeenCalled();expect((await s.flow.verify(email,'123456')).status).toBe('signed_in');});
it('password recovery verifies a code with the new password, without navigating to an external portal',async()=>{const s=setup();expect((await s.flow.resetPassword(email)).status).toBe('challenge');await expect(s.flow.verify(email,'123456','short')).rejects.toThrow('15');expect(s.signIn.attemptFirstFactor).not.toHaveBeenCalled();expect((await s.flow.verify(email,'123456','new-synthetic-password')).status).toBe('signed_in');expect(s.signIn.attemptFirstFactor).toHaveBeenCalledWith({strategy:'reset_password_email_code',code:'123456',password:'new-synthetic-password'});});
it('concurrent actions are rejected without sending another request or losing the current challenge',async()=>{const s=setup();let release!:(v:unknown)=>void;s.signIn.create.mockImplementation(()=>new Promise(resolve=>release=resolve));const first=s.flow.password(email,'password');await vi.waitFor(()=>expect(release).toBeTypeOf('function'));await expect(s.flow.password('another@example.invalid','password')).rejects.toThrow('正在处理');expect(s.flow.cancel()).toBe(false);release({status:'complete',createdSessionId:sid});await first;expect(s.signIn.create).toHaveBeenCalledTimes(1);});
it('SDK error objects are translated without exposing raw payloads or credential details',()=>{const value={errors:[{code:'form_password_incorrect',longMessage:'private echoed credential'}]};expect(clerkFlowError(value)).not.toContain('private');expect(clerkFlowError(value)).toContain('邮箱或密码');});
it('resuming an existing session cannot silently sign in a different email than the form',async()=>{const s=setup();s.sdk.session={id:sid,getToken:async()=>'synthetic-token'};s.sdk.user={id:'user_a',primaryEmailAddress:{emailAddress:email}};await expect(s.flow.resume('other@example.invalid')).rejects.toThrow('另一个邮箱');expect(s.confirm).not.toHaveBeenCalled();});
it('account changes during business-profile confirmation cannot report success for the previous login',async()=>{const s=setup();s.confirm.mockImplementation(async()=>{s.sdk.session={id:'sess_another',getToken:async()=>'different-synthetic-token'};return userSession;});await expect(s.flow.password(email,'password')).rejects.toThrow('账号已切换');});

it('password submission after desktop/OAuth sign-in reuses the matching session without another password request',async()=>{const s=setup();await s.sdk.setActive({session:sid});s.signIn.create.mockRejectedValue({errors:[{code:'session_exists'}]});expect((await s.flow.password(email.toUpperCase(),'unused-synthetic-password')).status).toBe('signed_in');expect(s.signIn.create).not.toHaveBeenCalled();expect(s.confirm).toHaveBeenCalledTimes(1);});
it('matching active session also skips unnecessary verification mail',async()=>{const s=setup();await s.sdk.setActive({session:sid});expect((await s.flow.emailCode(email)).status).toBe('signed_in');expect(s.signIn.create).not.toHaveBeenCalled();expect(s.signIn.prepareFirstFactor).not.toHaveBeenCalled();});
it('session_exists race can resume only after the same mailbox becomes active',async()=>{const s=setup();s.signIn.create.mockImplementation(async()=>{await s.sdk.setActive({session:sid});throw {errors:[{code:'session_exists'}]};});expect((await s.flow.password(email,'synthetic-password')).status).toBe('signed_in');expect(s.signIn.create).toHaveBeenCalledTimes(1);});
it('an active different mailbox neither authenticates the wrong account nor logs it out automatically',async()=>{const s=setup();await s.sdk.setActive({session:sid});await expect(s.flow.password('different@example.invalid','synthetic-password')).rejects.toThrow('另一个邮箱');expect(s.confirm).not.toHaveBeenCalled();expect(s.signIn.create).not.toHaveBeenCalled();expect(s.sdk.signOut).not.toHaveBeenCalled();});
it('business verification failure still rejects the reused session',async()=>{const s=setup();await s.sdk.setActive({session:sid});s.confirm.mockRejectedValue(Error('D1 unavailable'));await expect(s.flow.password(email,'synthetic-password')).rejects.toThrow('D1 unavailable');expect(s.signIn.create).not.toHaveBeenCalled();});
it('resuming cannot turn an empty or another mailbox profile into successful login',async()=>{for(const result of [null,{...userSession,email:'other@example.invalid'}]){const s=setup();await s.sdk.setActive({session:sid});s.confirm.mockResolvedValue(result as unknown as UserSession);await expect(s.flow.resume(email)).rejects.toThrow('同步未完成');}});
it('explicit account switch revokes only the active web session',async()=>{const s=setup();await s.sdk.setActive({session:sid});await s.flow.switchAccount();expect(s.sdk.signOut).toHaveBeenCalledExactlyOnceWith({sessionId:sid});expect(s.sdk.session).toBeNull();});
