import { describe, expect, it } from 'vitest';
import {
  MentorPhotoClientError,
  buildMentorPhotoDataUrl,
  isMentorPhotoCacheKey,
  resolveMentorPhotoFromHomepage
} from '../lib/desktop-mentor-photo';

describe('desktop mentor photo client boundary', () => {
  it('only accepts cache keys generated by the native image cache', () => {
    expect(isMentorPhotoCacheKey(`${'a'.repeat(64)}.jpg`)).toBe(true);
    expect(isMentorPhotoCacheKey(`${'f'.repeat(64)}.webp`)).toBe(true);
    expect(isMentorPhotoCacheKey('../mentor.jpg')).toBe(false);
    expect(isMentorPhotoCacheKey(`${'A'.repeat(64)}.jpg`)).toBe(true);
  });

  it('builds data URLs only for bounded raster image responses', () => {
    expect(buildMentorPhotoDataUrl('image/jpeg', '/9j/2Q==')).toBe('data:image/jpeg;base64,/9j/2Q==');
    expect(() => buildMentorPhotoDataUrl('image/svg+xml', 'PHN2Zz4=')).toThrow(MentorPhotoClientError);
    expect(() => buildMentorPhotoDataUrl('image/png', 'not base64')).toThrow(MentorPhotoClientError);
  });

  it('never falls back to browser fetch outside the installed Tauri client', async () => {
    const originalFetch = globalThis.fetch;
    let fetchCalled = false;
    globalThis.fetch = (async () => {
      fetchCalled = true;
      throw new Error('unexpected fetch');
    }) as typeof fetch;
    try {
      await expect(resolveMentorPhotoFromHomepage('https://faculty.example.edu/mentor')).rejects.toMatchObject({
        code: 'MENTOR_PHOTO_DESKTOP_ONLY'
      });
      expect(fetchCalled).toBe(false);
    } finally {
      globalThis.fetch = originalFetch;
    }
  });
});
