export type CompetitionLevel = 'A类' | 'B类' | '热门';
export type CompetitionDeadlineFilter = '全部' | '有截止时间' | '30天内' | '已过期' | '长期准备';

export type CompetitionItem = {
  id: string;
  title: string;
  shortName: string;
  level: CompetitionLevel;
  category: string;
  organizer: string;
  officialUrl: string;
  signupEnd: string;
  eventStart: string;
  eventEnd: string;
  hasDetails: boolean;
};

export const competitionItems: CompetitionItem[] = [
  {
    "id": "1",
    "title": "中国国际大学生创新大赛",
    "shortName": "互联网+",
    "level": "A类",
    "category": "创新创业",
    "organizer": "教育部 / 中央统战部 / 等",
    "officialUrl": "https://cy.ncss.cn/",
    "signupEnd": "2026-08-31",
    "eventStart": "2026-09-01",
    "eventEnd": "2026-09-30",
    "hasDetails": true
  },
  {
    "id": "2",
    "title": "\"挑战杯\"全国大学生课外学术科技作品竞赛",
    "shortName": "大挑战杯",
    "level": "A类",
    "category": "创新创业",
    "organizer": "共青团中央 / 中国科协 / 教育部 / 等",
    "officialUrl": "http://www.tiaozhanbei.net/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "3",
    "title": "\"挑战杯\"中国大学生创业计划竞赛",
    "shortName": "小挑战杯",
    "level": "A类",
    "category": "创新创业",
    "organizer": "共青团中央 / 教育部 / 等",
    "officialUrl": "http://www.tiaozhanbei.net/",
    "signupEnd": "",
    "eventStart": "2026-04-09",
    "eventEnd": "2026-04-24",
    "hasDetails": true
  },
  {
    "id": "4",
    "title": "ACM-ICPC 国际大学生程序设计竞赛(亚洲区)",
    "shortName": "ICPC 亚洲区",
    "level": "A类",
    "category": "计算机",
    "organizer": "ACM / ICPC 基金会",
    "officialUrl": "https://icpc.global/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "5",
    "title": "CCPC 中国大学生程序设计竞赛",
    "shortName": "CCPC",
    "level": "A类",
    "category": "计算机",
    "organizer": "CCPC 组委会",
    "officialUrl": "https://ccpc.io/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "6",
    "title": "蓝桥杯全国软件和信息技术专业人才大赛",
    "shortName": "蓝桥杯",
    "level": "A类",
    "category": "计算机",
    "organizer": "工业和信息化部人才交流中心",
    "officialUrl": "https://dasai.lanqiao.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "7",
    "title": "中国大学生计算机设计大赛",
    "shortName": "计设赛",
    "level": "A类",
    "category": "计算机",
    "organizer": "教育部高教司",
    "officialUrl": "http://2024.jsjds.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "8",
    "title": "中国软件杯大学生软件设计大赛",
    "shortName": "中国软件杯",
    "level": "A类",
    "category": "计算机",
    "organizer": "工信部 / 教育部 / 江苏省政府",
    "officialUrl": "http://www.cnsoftbei.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "9",
    "title": "全国大学生信息安全竞赛",
    "shortName": "信安赛",
    "level": "A类",
    "category": "计算机",
    "organizer": "教育部高等学校网络空间安全专业教学指导委员会",
    "officialUrl": "https://www.ciscn.cn/",
    "signupEnd": "",
    "eventStart": "2025-05-01",
    "eventEnd": "2025-08-31",
    "hasDetails": true
  },
  {
    "id": "10",
    "title": "全国高校大学生物联网设计竞赛",
    "shortName": "物联网设计赛",
    "level": "A类",
    "category": "计算机",
    "organizer": "教育部高等学校计算机类专业教学指导委员会",
    "officialUrl": "https://www.iotcontest.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "11",
    "title": "中国高校计算机大赛(C4)",
    "shortName": "C4",
    "level": "A类",
    "category": "计算机",
    "organizer": "全国高等学校计算机教育研究会 / 等",
    "officialUrl": "https://www.c4best.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "12",
    "title": "全国大学生集成电路创新创业大赛",
    "shortName": "集创赛",
    "level": "A类",
    "category": "计算机 / 电子",
    "organizer": "工信部人才交流中心 / 教育部高等学校集成电路科学与工程教学指导委员会",
    "officialUrl": "http://univ.ciciec.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "13",
    "title": "全国大学生嵌入式芯片与系统设计竞赛",
    "shortName": "嵌入式赛",
    "level": "A类",
    "category": "计算机 / 电子",
    "organizer": "中国电子学会 / 等",
    "officialUrl": "https://www.eetop.cn/embed_competition/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "14",
    "title": "全国大学生服务外包创新创业大赛",
    "shortName": "服务外包大赛",
    "level": "A类",
    "category": "计算机",
    "organizer": "教育部 / 商务部 / 江苏省政府",
    "officialUrl": "http://www.fwwbgj.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "15",
    "title": "全国大学生数学建模竞赛",
    "shortName": "数模国赛",
    "level": "A类",
    "category": "数学",
    "organizer": "中国工业与应用数学学会(CSIAM)",
    "officialUrl": "http://www.mcm.edu.cn/",
    "signupEnd": "",
    "eventStart": "2026-09-10",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "16",
    "title": "美国大学生数学建模竞赛(MCM/ICM)",
    "shortName": "美赛",
    "level": "A类",
    "category": "数学",
    "organizer": "COMAP",
    "officialUrl": "https://www.comap.com/contests/mcm-icm",
    "signupEnd": "",
    "eventStart": "2026-01-29",
    "eventEnd": "2026-02-02",
    "hasDetails": true
  },
  {
    "id": "17",
    "title": "全国大学生数学竞赛",
    "shortName": "数学竞赛",
    "level": "A类",
    "category": "数学",
    "organizer": "中国数学会",
    "officialUrl": "https://www.cms.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "18",
    "title": "全国大学生物理学术竞赛(CUPT)",
    "shortName": "CUPT",
    "level": "A类",
    "category": "物理",
    "organizer": "教育部高等学校物理基础课程教学指导委员会",
    "officialUrl": "http://cupt.bnu.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "19",
    "title": "全国大学生物理实验竞赛",
    "shortName": "物理实验赛",
    "level": "A类",
    "category": "物理",
    "organizer": "教育部高等学校物理基础课程教学指导委员会",
    "officialUrl": "http://www.cupem.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "20",
    "title": "全国大学生化学实验创新设计大赛",
    "shortName": "化学实验赛",
    "level": "A类",
    "category": "化学",
    "organizer": "教育部高等学校化学类专业教学指导委员会",
    "officialUrl": "https://www.zghxss.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "21",
    "title": "全国大学生生命科学竞赛",
    "shortName": "生命科学竞赛",
    "level": "A类",
    "category": "生命科学",
    "organizer": "高等学校生物科学类专业教学指导委员会",
    "officialUrl": "http://www.bioinnovation.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "22",
    "title": "全国大学生机械创新设计大赛",
    "shortName": "机械创新赛",
    "level": "A类",
    "category": "机械",
    "organizer": "教育部高等学校机械类专业教学指导委员会",
    "officialUrl": "http://www.cmcc.net.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "23",
    "title": "全国大学生工程训练综合能力竞赛",
    "shortName": "工训赛",
    "level": "A类",
    "category": "机械 / 综合工程",
    "organizer": "教育部高教司",
    "officialUrl": "https://gcxl.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "24",
    "title": "全国大学生结构设计竞赛",
    "shortName": "结构赛",
    "level": "A类",
    "category": "土木 / 结构",
    "organizer": "教育部 / 住房和城乡建设部 / 等",
    "officialUrl": "http://www.structurecontest.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "25",
    "title": "全国周培源大学生力学竞赛",
    "shortName": "周培源力学竞赛",
    "level": "A类",
    "category": "力学",
    "organizer": "中国力学学会 / 周培源基金会",
    "officialUrl": "http://www.zpy.cstam.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "26",
    "title": "全国大学生先进成图技术与产品信息建模创新大赛",
    "shortName": "成图大赛",
    "level": "A类",
    "category": "机械 / 工程图学",
    "organizer": "中国图学学会",
    "officialUrl": "http://www.zgxh.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "27",
    "title": "全国大学生机器人大赛 RoboMaster",
    "shortName": "RoboMaster",
    "level": "A类",
    "category": "机械 / 自动化",
    "organizer": "DJI 大疆 / 共青团中央",
    "officialUrl": "https://www.robomaster.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "28",
    "title": "全国大学生机器人大赛 RoboCon",
    "shortName": "RoboCon",
    "level": "A类",
    "category": "机械 / 自动化",
    "organizer": "共青团中央 / 央视",
    "officialUrl": "http://www.robocon.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "29",
    "title": "全国大学生工程实践与创新能力大赛",
    "shortName": "i 创杯",
    "level": "A类",
    "category": "工程综合",
    "organizer": "教育部高教司",
    "officialUrl": "https://i-eic.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "30",
    "title": "全国大学生节能减排社会实践与科技竞赛",
    "shortName": "节能减排大赛",
    "level": "A类",
    "category": "工程 / 环境",
    "organizer": "教育部高教司",
    "officialUrl": "http://www.jienengjianpai.org/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "31",
    "title": "全国大学生光电设计竞赛",
    "shortName": "光电设计赛",
    "level": "A类",
    "category": "光电 / 仪器",
    "organizer": "教育部高等学校光电信息科学与工程专业教学指导分委员会",
    "officialUrl": "http://www.gddesign.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "32",
    "title": "全国大学生金相技能大赛",
    "shortName": "金相大赛",
    "level": "A类",
    "category": "材料",
    "organizer": "教育部高等学校材料类专业教学指导委员会",
    "officialUrl": "http://www.metallographyc.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "33",
    "title": "全国大学生焊接创新大赛",
    "shortName": "焊接创新大赛",
    "level": "A类",
    "category": "材料 / 制造",
    "organizer": "中国焊接协会",
    "officialUrl": "http://www.cwa.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "34",
    "title": "\"西门子杯\"中国智能制造挑战赛",
    "shortName": "西门子杯",
    "level": "A类",
    "category": "自动化 / 智能制造",
    "organizer": "教育部高等学校自动化类专业教学指导委员会 / 西门子",
    "officialUrl": "http://www.siemenscup-cimc.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "35",
    "title": "\"恩智浦杯\"全国大学生智能汽车竞赛",
    "shortName": "智能车",
    "level": "A类",
    "category": "电子 / 自动化",
    "organizer": "教育部高等学校自动化类专业教学指导委员会",
    "officialUrl": "https://www.smartcar.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "36",
    "title": "全国大学生电子设计竞赛",
    "shortName": "电赛",
    "level": "A类",
    "category": "电子",
    "organizer": "教育部高教司 / 工信部人事教育司",
    "officialUrl": "http://nuedc.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "37",
    "title": "\"TI 杯\"全国大学生电子设计竞赛模拟电子系统专题邀请赛",
    "shortName": "TI 杯模拟",
    "level": "A类",
    "category": "电子",
    "organizer": "TI 中国 / 教育部高教司",
    "officialUrl": "https://www.ti.com.cn/event/cn/educators/contest.html",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "38",
    "title": "全国大学生电子商务\"创新、创意及创业\"挑战赛",
    "shortName": "三创赛",
    "level": "A类",
    "category": "电子商务 / 创新创业",
    "organizer": "教育部高等学校电子商务类专业教学指导委员会",
    "officialUrl": "http://www.3chuang.net/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "39",
    "title": "全国大学生电气电子工程创新大赛",
    "shortName": "电气创新赛",
    "level": "A类",
    "category": "电气",
    "organizer": "中国电机工程学会",
    "officialUrl": "https://www.csee.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "40",
    "title": "\"飞思卡尔\"全国大学生智能互联创新大赛",
    "shortName": "智能互联创新赛",
    "level": "A类",
    "category": "电子 / IoT",
    "organizer": "NXP / 教育部高教司",
    "officialUrl": "https://www.smartcar.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "41",
    "title": "全国大学生化工设计竞赛",
    "shortName": "化工设计赛",
    "level": "A类",
    "category": "化工",
    "organizer": "中国化工学会",
    "officialUrl": "http://www.iche8.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "42",
    "title": "全国大学生制药工程设计竞赛",
    "shortName": "制药设计赛",
    "level": "A类",
    "category": "制药",
    "organizer": "中国化工教育协会 / 中国化工学会制药工程专业委员会",
    "officialUrl": "http://www.zhipiaopaisai.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "43",
    "title": "全国大学生化工实验大赛",
    "shortName": "化工实验赛",
    "level": "A类",
    "category": "化工",
    "organizer": "中国化工教育协会",
    "officialUrl": "http://www.iche8.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "44",
    "title": "全国大学生先进材料创新创意大赛",
    "shortName": "先进材料赛",
    "level": "A类",
    "category": "材料",
    "organizer": "中国硅酸盐学会",
    "officialUrl": "http://www.iccsm.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "45",
    "title": "全国大学生高分子材料创新创业大赛",
    "shortName": "高分子赛",
    "level": "A类",
    "category": "材料",
    "organizer": "中国化工学会",
    "officialUrl": "http://www.gfzcyds.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "46",
    "title": "全国大学生市场调查与分析大赛",
    "shortName": "市调赛",
    "level": "A类",
    "category": "经管 / 统计",
    "organizer": "教育部高等学校统计学类专业教学指导委员会",
    "officialUrl": "http://www.cnstats.org/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "47",
    "title": "全国大学生统计建模大赛",
    "shortName": "统计建模赛",
    "level": "A类",
    "category": "统计",
    "organizer": "中国统计教育学会",
    "officialUrl": "http://www.tjjmds.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "48",
    "title": "全国大学生金融科技创新能力大赛",
    "shortName": "金融科技赛",
    "level": "A类",
    "category": "金融",
    "organizer": "教育部高等学校金融学类专业教学指导委员会",
    "officialUrl": "http://www.jrkj.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "49",
    "title": "全国大学生金融精英挑战赛",
    "shortName": "金融精英赛",
    "level": "A类",
    "category": "金融",
    "organizer": "中国金融学会金融教育专业委员会",
    "officialUrl": "http://www.cufe.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "50",
    "title": "\"学创杯\"全国大学生创业综合模拟大赛",
    "shortName": "学创杯",
    "level": "A类",
    "category": "创新创业 / 经管",
    "organizer": "教育部高等学校经济与贸易类专业教学指导委员会",
    "officialUrl": "http://www.xuechuangbei.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "51",
    "title": "\"中国高校商业精英挑战赛\" 全国会展专业创新创业实践竞赛",
    "shortName": "会展赛",
    "level": "A类",
    "category": "会展",
    "organizer": "中国会展经济研究会",
    "officialUrl": "http://www.zghxh.org/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "52",
    "title": "全国大学生人力资源管理知识技能竞赛",
    "shortName": "人力资源赛",
    "level": "A类",
    "category": "管理",
    "organizer": "中国人力资源开发研究会",
    "officialUrl": "http://www.ehrcia.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "53",
    "title": "\"外研社·国才杯\"\"理解当代中国\"全国大学生外语能力大赛",
    "shortName": "外研社国才杯",
    "level": "A类",
    "category": "外语",
    "organizer": "外研社 / 国才考试",
    "officialUrl": "https://uchallenge.unipus.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "54",
    "title": "全国大学生英语竞赛",
    "shortName": "英语竞赛 NECCS",
    "level": "A类",
    "category": "外语",
    "organizer": "高等学校大学外语教学研究会",
    "officialUrl": "http://www.dxsyy.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "55",
    "title": "\"21 世纪杯\"全国英语演讲比赛",
    "shortName": "21 世纪杯",
    "level": "A类",
    "category": "外语",
    "organizer": "21 世纪英文报",
    "officialUrl": "https://www.21stcentury.com.cn/speech/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "56",
    "title": "全国大学生日语演讲比赛",
    "shortName": "日语演讲赛",
    "level": "A类",
    "category": "外语",
    "organizer": "中国日语教学研究会 / 日本国际交流基金会",
    "officialUrl": "http://www.cjlu.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "57",
    "title": "\"卡西欧杯\"翻译竞赛",
    "shortName": "卡西欧翻译赛",
    "level": "A类",
    "category": "外语",
    "organizer": "上海翻译家协会",
    "officialUrl": "http://www.shanghaitranslator.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "58",
    "title": "全国大学生医学技术技能大赛",
    "shortName": "医学技能赛",
    "level": "A类",
    "category": "医学",
    "organizer": "教育部高教司 / 国家卫生健康委",
    "officialUrl": "https://yxjnds.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "59",
    "title": "全国高等医学院校大学生临床技能竞赛",
    "shortName": "临床技能赛",
    "level": "A类",
    "category": "医学",
    "organizer": "教育部高等学校临床医学类专业教学指导委员会",
    "officialUrl": "http://www.cmda.net/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "60",
    "title": "全国大学生药苑论坛创新成果展评",
    "shortName": "药苑论坛",
    "level": "A类",
    "category": "药学",
    "organizer": "高等学校药学类专业教学指导委员会",
    "officialUrl": "http://www.cpu.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "61",
    "title": "全国中医大学生创意大赛",
    "shortName": "中医创意赛",
    "level": "A类",
    "category": "医学",
    "organizer": "中华中医药学会",
    "officialUrl": "http://www.cacm.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "62",
    "title": "全国大学生口腔医学知识竞赛",
    "shortName": "口腔医学赛",
    "level": "A类",
    "category": "医学",
    "organizer": "中华口腔医学会",
    "officialUrl": "https://www.cndent.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "63",
    "title": "全国大学生动物医学专业技能大赛",
    "shortName": "动医技能赛",
    "level": "A类",
    "category": "农林 / 兽医",
    "organizer": "中国农业大学 / 全国动物医学学科",
    "officialUrl": "http://cau.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "64",
    "title": "全国大学生植物保护专业能力大赛",
    "shortName": "植保赛",
    "level": "A类",
    "category": "农林 / 植保",
    "organizer": "教育部高等学校植物生产类专业教学指导委员会",
    "officialUrl": "http://www.zhibao.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "65",
    "title": "全国大学生水产技能大赛",
    "shortName": "水产技能赛",
    "level": "A类",
    "category": "农林 / 水产",
    "organizer": "教育部高等学校水产类专业教学指导委员会",
    "officialUrl": "http://shuichan.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "66",
    "title": "全国大学生农业建筑环境与能源工程相关专业创新创业大赛",
    "shortName": "农建赛",
    "level": "A类",
    "category": "农林 / 工程",
    "organizer": "教育部高等学校农业工程类专业教学指导委员会",
    "officialUrl": "http://nongjianbei.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "67",
    "title": "\"挑战杯彩虹人生\"全国职业学校创新创效创业大赛",
    "shortName": "挑战杯彩虹人生",
    "level": "A类",
    "category": "创新创业",
    "organizer": "共青团中央 / 教育部",
    "officialUrl": "http://www.tiaozhanbei.net/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "68",
    "title": "全国大学生广告艺术大赛",
    "shortName": "大广赛",
    "level": "A类",
    "category": "艺术 / 广告",
    "organizer": "教育部高等学校新闻传播学类专业教学指导委员会",
    "officialUrl": "https://www.sun-ada.net/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "69",
    "title": "米兰设计周-中国高校设计学科师生优秀作品展",
    "shortName": "米兰设计周",
    "level": "A类",
    "category": "艺术 / 设计",
    "organizer": "中国轻工业联合会 / 中国包装联合会",
    "officialUrl": "http://www.mldsz.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "70",
    "title": "全国大学生工业设计大赛",
    "shortName": "工业设计赛",
    "level": "A类",
    "category": "设计",
    "organizer": "教育部高等学校工业设计专业教学指导分委员会",
    "officialUrl": "http://www.gysjds.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "71",
    "title": "\"中国大学生文学作品大赛\"",
    "shortName": "大学生文学作品大赛",
    "level": "A类",
    "category": "文学",
    "organizer": "中华文学基金会 / 等",
    "officialUrl": "http://www.zhwxjjh.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "72",
    "title": "\"汉仪杯\"全国大学生字体设计大赛",
    "shortName": "汉仪字体赛",
    "level": "A类",
    "category": "设计",
    "organizer": "汉仪字库 / 等",
    "officialUrl": "http://www.hanyi.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "73",
    "title": "全国大学生讲思政课公开课展示活动",
    "shortName": "思政公开课",
    "level": "A类",
    "category": "思政",
    "organizer": "教育部高等学校思想政治理论课教学指导委员会",
    "officialUrl": "http://www.cflac.org.cn/",
    "signupEnd": "",
    "eventStart": "2026-04-26",
    "eventEnd": "2026-04-26",
    "hasDetails": true
  },
  {
    "id": "74",
    "title": "全国大学生法治辩论赛",
    "shortName": "法治辩论赛",
    "level": "A类",
    "category": "法律",
    "organizer": "中国法学会",
    "officialUrl": "http://www.chinalaw.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "75",
    "title": "全国大学生模拟法庭竞赛",
    "shortName": "模拟法庭赛",
    "level": "A类",
    "category": "法律",
    "organizer": "教育部高等学校法学类专业教学指导委员会",
    "officialUrl": "http://www.chinalaw.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "76",
    "title": "全国大学生社会调查报告大赛",
    "shortName": "社调赛",
    "level": "A类",
    "category": "社会学",
    "organizer": "中国社会学会",
    "officialUrl": "http://www.sociologyol.org/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "77",
    "title": "全国大学生测绘学科创新创业智能大赛",
    "shortName": "测绘大赛",
    "level": "A类",
    "category": "测绘",
    "organizer": "教育部高等学校测绘类专业教学指导委员会",
    "officialUrl": "http://www.cncxl.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "78",
    "title": "全国大学生地质技能竞赛",
    "shortName": "地质技能赛",
    "level": "A类",
    "category": "地球科学",
    "organizer": "教育部高等学校地质学类专业教学指导委员会",
    "officialUrl": "http://www.dzjnjs.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "79",
    "title": "全国大学生水利创新设计大赛",
    "shortName": "水利创新赛",
    "level": "A类",
    "category": "水利",
    "organizer": "中国水利学会",
    "officialUrl": "http://www.xinshui.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "80",
    "title": "全国海洋航行器设计与制作大赛",
    "shortName": "海洋航行器大赛",
    "level": "A类",
    "category": "海洋 / 工程",
    "organizer": "工信部 / 中国造船工程学会",
    "officialUrl": "http://www.simunews.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "81",
    "title": "全国大学生武术锦标赛",
    "shortName": "武术锦标赛",
    "level": "A类",
    "category": "体育",
    "organizer": "中国大学生体育协会",
    "officialUrl": "http://www.cufss.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "82",
    "title": "全国大学生健康教育大赛",
    "shortName": "健康教育赛",
    "level": "A类",
    "category": "医学 / 健康",
    "organizer": "中国大学生体育协会",
    "officialUrl": "http://www.cufss.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "83",
    "title": "中国大学生方程式系列赛事(FSC/FSE/FSAC)",
    "shortName": "FSC 方程式",
    "level": "A类",
    "category": "交通 / 汽车",
    "organizer": "中国汽车工程学会",
    "officialUrl": "https://www.formulastudent.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "84",
    "title": "全国大学生交通运输科技大赛",
    "shortName": "交通科技赛",
    "level": "A类",
    "category": "交通",
    "organizer": "教育部高等学校交通运输类专业教学指导委员会",
    "officialUrl": "http://www.cnncts.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "85",
    "title": "全国高校商业精英挑战赛 - 创新创业竞赛",
    "shortName": "商业精英赛",
    "level": "A类",
    "category": "商科",
    "organizer": "中国国际贸易促进委员会商业行业委员会",
    "officialUrl": "http://www.bechallenge.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "97",
    "title": "\"CCF BDCI\" 中国大数据与计算智能大赛",
    "shortName": "BDCI",
    "level": "B类",
    "category": "计算机 / 大数据",
    "organizer": "中国计算机学会 (CCF)",
    "officialUrl": "https://www.datafountain.cn/competitions/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "101",
    "title": "\"全国高校计算机能力挑战赛\"",
    "shortName": "计算机能力挑战赛",
    "level": "B类",
    "category": "计算机",
    "organizer": "工信部人才交流中心",
    "officialUrl": "http://www.ncccu.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "102",
    "title": "\"中国高校计算机大赛 - 团体程序设计天梯赛\"",
    "shortName": "GPLT / 天梯赛",
    "level": "B类",
    "category": "计算机",
    "organizer": "全国高等学校计算机教育研究会",
    "officialUrl": "https://gplt.patest.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "103",
    "title": "\"全国高校大学生 RoboCup 仿真组比赛\"",
    "shortName": "RoboCup 仿真",
    "level": "B类",
    "category": "计算机 / 机器人",
    "organizer": "RoboCup China",
    "officialUrl": "http://www.robocup.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "104",
    "title": "\"创青春\"全国大学生创业大赛",
    "shortName": "创青春",
    "level": "B类",
    "category": "创新创业",
    "organizer": "共青团中央 / 教育部",
    "officialUrl": "http://cy.youth.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "105",
    "title": "\"高教社杯\"全国大学生先进成图技术赛",
    "shortName": "成图大赛",
    "level": "B类",
    "category": "工程图学",
    "organizer": "中国图学学会",
    "officialUrl": "http://www.zgxh.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "107",
    "title": "\"中国 MBA 创业大赛\"(本科生组)",
    "shortName": "MBA 创业赛",
    "level": "B类",
    "category": "商科",
    "organizer": "中国 MBA 教育指导委员会",
    "officialUrl": "https://www.mba.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "108",
    "title": "\"全国大学生综合管理决策大赛\"",
    "shortName": "管理决策赛",
    "level": "B类",
    "category": "管理",
    "organizer": "中国管理科学学会",
    "officialUrl": "http://www.gldcs.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "109",
    "title": "\"全国大学生市场营销策划大赛\"",
    "shortName": "市场营销赛",
    "level": "B类",
    "category": "商科 / 营销",
    "organizer": "中国市场学会",
    "officialUrl": "http://www.cma-jh.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "110",
    "title": "\"21 世纪杯·全国大学生英语写作大赛\"",
    "shortName": "21 世纪英语写作",
    "level": "B类",
    "category": "外语",
    "organizer": "21 世纪英文报",
    "officialUrl": "https://www.21stcentury.com.cn/competition/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "111",
    "title": "\"中国日报 21 世纪杯\"全国大学生英语演讲",
    "shortName": "21 世纪演讲",
    "level": "B类",
    "category": "外语",
    "organizer": "中国日报社 / 21 世纪英文报",
    "officialUrl": "https://www.21stcentury.com.cn/speech/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "112",
    "title": "\"CCTV 杯\"全国英语演讲大赛",
    "shortName": "CCTV 杯英演",
    "level": "B类",
    "category": "外语",
    "organizer": "CCTV / 北京外国语大学",
    "officialUrl": "http://www.beipress.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "113",
    "title": "\"全国大学生数字媒体科技作品及创意竞赛\"",
    "shortName": "数媒大赛",
    "level": "B类",
    "category": "设计 / 数媒",
    "organizer": "教育部高等学校数字媒体专业教学指导分委员会",
    "officialUrl": "http://www.gdds.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "114",
    "title": "\"未来设计师·全国高校数字艺术设计大赛(NCDA)\"",
    "shortName": "NCDA",
    "level": "B类",
    "category": "设计",
    "organizer": "NCDA 组委会 / 教育部",
    "officialUrl": "https://www.ncda.org.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "115",
    "title": "\"博创杯\"全国大学生嵌入式物联网设计大赛",
    "shortName": "博创杯",
    "level": "B类",
    "category": "电子 / IoT",
    "organizer": "北京博创智联科技 / 教育部",
    "officialUrl": "http://www.bccoa.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "116",
    "title": "\"飞思卡尔\"全国大学生智能车竞赛",
    "shortName": "智能车竞赛 (飞思卡尔)",
    "level": "B类",
    "category": "电子 / 自动化",
    "organizer": "NXP / 教育部",
    "officialUrl": "https://www.smartcar.com.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "117",
    "title": "\"工程实践与创新能力大赛\"",
    "shortName": "工创赛",
    "level": "B类",
    "category": "工程 / 综合",
    "organizer": "教育部高等学校工程训练教学指导委员会",
    "officialUrl": "https://i-eic.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "86",
    "title": "\"妈妈杯\"中国大学生数学建模挑战赛",
    "shortName": "MathorCup / 妈妈杯",
    "level": "热门",
    "category": "数学",
    "organizer": "中国优选法统筹法与经济数学研究会",
    "officialUrl": "http://mathorcup.org/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "87",
    "title": "\"五一杯\"全国大学生数学建模竞赛",
    "shortName": "五一数模赛",
    "level": "热门",
    "category": "数学",
    "organizer": "中国矿业大学 / 数学中国",
    "officialUrl": "http://www.51mcm.cumt.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "88",
    "title": "\"认证杯\"数学中国数学建模国际赛",
    "shortName": "认证杯 / 小美赛",
    "level": "热门",
    "category": "数学",
    "organizer": "数学中国 / 美国 COMAP",
    "officialUrl": "http://mcm.tzmcm.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "89",
    "title": "\"数维杯\"大学生数学建模挑战赛",
    "shortName": "数维杯",
    "level": "热门",
    "category": "数学",
    "organizer": "陕西省国际科技合作协会",
    "officialUrl": "http://www.shumoweb.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "90",
    "title": "\"亚太地区大学生数学建模竞赛\"",
    "shortName": "APMCM 亚太赛",
    "level": "热门",
    "category": "数学",
    "organizer": "北京图象图形学学会 / APMCM 组委会",
    "officialUrl": "http://www.apmcm.org/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "91",
    "title": "\"深圳杯\"数学建模挑战赛",
    "shortName": "深圳杯",
    "level": "热门",
    "category": "数学",
    "organizer": "中国工业与应用数学学会 / 深圳市政府",
    "officialUrl": "http://www.m2cai.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "92",
    "title": "\"华中杯\"大学生数学建模挑战赛",
    "shortName": "华中杯",
    "level": "热门",
    "category": "数学",
    "organizer": "中国工业与应用数学学会 华中分会",
    "officialUrl": "http://www.hzbmcm.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "93",
    "title": "\"华东杯\"大学生数学建模邀请赛",
    "shortName": "华东杯",
    "level": "热门",
    "category": "数学",
    "organizer": "上海财经大学 / 华东数模联盟",
    "officialUrl": "http://hdb.shufe.edu.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "94",
    "title": "\"中青杯\"全国大学生数学建模竞赛",
    "shortName": "中青杯",
    "level": "热门",
    "category": "数学",
    "organizer": "中国青少年发展服务中心",
    "officialUrl": "http://www.zhongqingbei.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "95",
    "title": "\"东三省\"数学建模联赛",
    "shortName": "东三省赛",
    "level": "热门",
    "category": "数学",
    "organizer": "辽宁省数学学会 / 东三省高校",
    "officialUrl": "http://www.dscmcm.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "96",
    "title": "阿里云天池大赛",
    "shortName": "天池大赛",
    "level": "热门",
    "category": "计算机 / 数据科学",
    "organizer": "阿里云",
    "officialUrl": "https://tianchi.aliyun.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": true
  },
  {
    "id": "98",
    "title": "\"百度飞桨\" PaddlePaddle 全国 AI 大赛",
    "shortName": "飞桨 AI 大赛",
    "level": "热门",
    "category": "计算机 / AI",
    "organizer": "百度飞桨",
    "officialUrl": "https://aistudio.baidu.com/competition",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "99",
    "title": "\"华为软件精英挑战赛\"",
    "shortName": "华为软挑",
    "level": "热门",
    "category": "计算机",
    "organizer": "华为",
    "officialUrl": "https://codecraft.huawei.com/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "100",
    "title": "\"OpenHarmony\"创新大赛",
    "shortName": "OpenHarmony 大赛",
    "level": "热门",
    "category": "计算机 / 操作系统",
    "organizer": "OpenAtom 开源基金会 / 教育部",
    "officialUrl": "https://www.openharmonycontest.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  },
  {
    "id": "106",
    "title": "\"KAB 创业之星\"大学生创业大赛",
    "shortName": "KAB 创业之星",
    "level": "热门",
    "category": "创新创业",
    "organizer": "团中央 / KAB",
    "officialUrl": "http://kab.youth.cn/",
    "signupEnd": "",
    "eventStart": "",
    "eventEnd": "",
    "hasDetails": false
  }
];

export const competitionLevelOptions = ['全部', 'A类', 'B类', '热门'] as const;
export const competitionDeadlineOptions = ['全部', '有截止时间', '30天内', '已过期', '长期准备'] as const;

export function getCompetitionCategories() {
  const categories = new Set<string>();

  for (const item of competitionItems) {
    item.category
      .split('/')
      .map((entry) => entry.trim())
      .filter(Boolean)
      .forEach((entry) => categories.add(entry));
  }

  return ['全部', ...Array.from(categories).sort((left, right) => left.localeCompare(right, 'zh-CN'))];
}

export function getCompetitionLevelCount(level: CompetitionLevel) {
  return competitionItems.filter((item) => item.level === level).length;
}
