export const QQ_GROUP_NUMBER = '1092490793';

// QQ group invite tokens are generated by QQ itself. Until an official invite
// link is configured, keep the group number visible in every entry point.
export const QQ_GROUP_URL = `https://qm.qq.com/cgi-bin/qm/qr?k=${QQ_GROUP_NUMBER}`;
