'use client';
import {createD1BackendClient} from './d1-backend-client';import {d1ClientForUser} from './clerk-d1-session';
let sharedPublicClient:ReturnType<typeof createD1BackendClient>|undefined;
function publicClient(){const base=process.env.NEXT_PUBLIC_D1_API_URL;if(base!=='https://migration.seekoffer.com.cn')throw Error('社区接口尚未配置。');return sharedPublicClient??=createD1BackendClient(base,async()=>null);}
export async function readCommunityPage(query:URLSearchParams,signal?:AbortSignal){const result=await publicClient().communityPosts(query,signal);if(!Array.isArray(result.items)||!Number.isSafeInteger(result.pagination?.totalPages)||result.pagination.totalPages<1||!Number.isSafeInteger(result.pagination.total)||result.items.length>40||!result.metrics||Object.values(result.metrics).some(v=>!Number.isSafeInteger(v)||v<0))throw Error('社区响应不完整。');return result;}
export async function readCommunityPosts(){return (await readCommunityPage(new URLSearchParams({page:'1',pageSize:'16'}))).items;}
export async function readCommunityComments(postId:string){const client=publicClient(),items:Record<string,unknown>[]=[];let page:number|null=1;while(page){const result=await client.communityComments(postId,page);if(!Array.isArray(result.items)||result.nextPage!==null&&result.nextPage!==page+1)throw Error('回复响应不完整。');items.push(...result.items);page=result.nextPage;}return items;}
export async function readCommunityFollows(owner:string){const client=await d1ClientForUser(owner),ids:string[]=[];let page:number|null=1;while(page){const result=await client.communityFollows(page);if(!Array.isArray(result.ids)||result.nextPage!==null&&result.nextPage!==page+1)throw Error('关注记录响应不完整。');ids.push(...result.ids);page=result.nextPage;}return ids;}
async function replayId(owner:string,resource:string,payload:Record<string,unknown>){const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(payload))))].map(b=>b.toString(16).padStart(2,'0')).join('');const key='seekoffer-community-request:'+owner+':'+resource+':'+hash;let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID();localStorage.setItem(key,value);}return{key,id:value};}
export async function writeCommunity(owner:string,resource:'posts'|'comments'|'follows',payload:Record<string,unknown>){const client=await d1ClientForUser(owner);if(resource==='follows')return client.communityWrite(resource,payload);const replay=await replayId(owner,resource,payload);const result=await client.communityWrite(resource,{...payload,requestId:replay.id}) as {id?:string;reviewStatus?:string};if(!result||result.id!==replay.id||!['pending','approved','rejected','hidden','deleted'].includes(result.reviewStatus||''))throw Error('提交结果尚未确认，草稿已保留。');localStorage.removeItem(replay.key);return result;}
export async function writeCommunityReport(postId:string,content:string,owner?:string|null){const client=owner?await d1ClientForUser(owner):publicClient();const payload={postId,content},replay=await replayId(owner||'anonymous','report',payload);const result=await client.communityReport({...payload,requestId:replay.id},Boolean(owner)) as {id?:string};if(!result||typeof result.id!=='string'||!result.id)throw Error('举报结果尚未确认，请保留内容。');localStorage.removeItem(replay.key);return result;}
